"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import { ErrorState, LoadingState, EmptyState } from "@/components/ui/AsyncState";
import { demoDashboard } from "@/lib/demo/player-demo";

type DashboardData = typeof demoDashboard;
export default function DashboardClient({username}:{username:string}){
 const [data,setData]=useState<DashboardData|null>(null);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);try{if(username.toLowerCase()==="demo"){setData(demoDashboard);return}const r=await fetch(`/api/players/${encodeURIComponent(username)}/dashboard`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load dashboard");setData(b)}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard")}},[username]);
 useEffect(()=>{load()},[load]);
 if(error)return <AppShell username={username}><ErrorState title="Could not load dashboard" message={error} onRetry={load}/></AppShell>;
 if(!data)return <AppShell username={username}><LoadingState title="Loading player dashboard..."/></AppShell>;
 const wins=data.resultSeries.filter(x=>x.result==="win").length, draws=data.resultSeries.filter(x=>x.result==="draw").length, losses=data.resultSeries.filter(x=>x.result==="loss").length;
 const max=Math.max(1,wins,draws,losses);
 return <AppShell username={username}><main className="mx-auto max-w-[1500px] px-4 py-7 lg:px-8"><header className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Chesslysis · Player Intelligence</p><h1 className="mt-2 text-3xl font-bold">Overview Dashboard</h1><p className="mt-2 text-sm text-slate-400">{data.username} · Performance patterns across analyzed games</p></div><div className="font-mono text-xs text-slate-500">24 games · Updated now</div></header>
 {data.stats.gamesAnalyzed===0?<EmptyState title="No analyzed games yet" message="Import and analyze games to unlock the intelligence dashboard."/>:<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Games analyzed" value={String(data.stats.gamesAnalyzed)} accent="cyan"/><Stat label="Win rate" value={`${data.stats.winRate.toFixed(1)}%`} accent="green"/><Stat label="Average accuracy" value={`${data.stats.averageAccuracy.toFixed(1)}%`} accent="violet"/><Stat label="Average ACPL" value={data.stats.averageACPL.toFixed(1)} accent="amber"/><Stat label="Blunders / game" value={data.stats.blundersPerGame.toFixed(2)} accent="red"/></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Accuracy trend & activity</h2><p className="mt-1 text-xs text-slate-500">Most recent analyzed games</p></div><span className="font-mono text-3xl font-bold text-white">{data.stats.averageAccuracy.toFixed(1)}%</span></div><Trend points={data.accuracyTrend}/></div><div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><h2 className="font-semibold">Results distribution</h2><div className="mt-6 space-y-5">{[["Wins",wins,"bg-emerald-400"],["Draws",draws,"bg-cyan-400"],["Losses",losses,"bg-red-400"]].map(([l,v,c])=><div key={String(l)}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-400">{l}</span><span className="font-mono">{v}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${c}`} style={{width:`${Number(v)/max*100}%`}}/></div></div>)}</div><Link href={`/insights/${encodeURIComponent(username)}`} className="mt-7 block rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-4 transition hover:bg-cyan-400/10"><span className="text-xs uppercase tracking-wider text-cyan-300">Automatic Insights Engine</span><p className="mt-2 font-semibold">Explore profile-level strengths and weaknesses →</p></Link></div></section>
 <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Recent games={data.recentGames}/><div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><span className="text-xs font-semibold uppercase tracking-wider text-violet-400">Next focus</span><h2 className="mt-3 text-xl font-bold">Find what keeps repeating.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Phase 2.3 clusters mistakes across multiple games so you can distinguish a one-off blunder from a real weakness.</p><Link href={`/mistakes/${encodeURIComponent(username)}`} className="mt-5 inline-block rounded-lg bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white">Detect recurring mistakes →</Link></div></section></>}</main></AppShell>;
}
function Stat({label,value,accent}:{label:string;value:string;accent:string}){const a:any={cyan:"text-cyan-300",green:"text-emerald-300",violet:"text-violet-300",amber:"text-amber-300",red:"text-red-300"};return <div className="rounded-2xl border border-white/10 bg-[#0d1320] p-5"><div className="text-xs uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-3 font-mono text-3xl font-bold ${a[accent]}`}>{value}</div></div>}
function Trend({points}:{points:{accuracy:number}[]}){const w=760,h=250;if(!points.length)return <div className="grid h-64 place-items-center text-sm text-slate-500">No trend data</div>;const d=points.map((p,i)=>{const x=points.length===1?w/2:i/(points.length-1)*w;const y=h-15-(Math.max(0,Math.min(100,p.accuracy))/100)*(h-30);return `${i?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)}`}).join(" ");return <svg viewBox={`0 0 ${w} ${h}`} className="h-64 w-full overflow-visible"><defs><linearGradient id="g" x1="0" x2="1"><stop stopColor="#22d3ee"/><stop offset="1" stopColor="#8b5cf6"/></linearGradient></defs>{[.25,.5,.75].map(x=><line key={x} x1="0" x2={w} y1={h*x} y2={h*x} stroke="white" opacity=".08"/>)}<path d={d} fill="none" stroke="url(#g)" strokeWidth="4" strokeLinecap="round"/></svg>}
function Recent({games}:{games:DashboardData["recentGames"]}){return <div id="games" className="overflow-hidden rounded-2xl border border-white/10 bg-[#0d1320]"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">Recent analyzed games</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="bg-white/[.025] text-left text-[11px] uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Opponent</th><th>Color</th><th>Result</th><th>Time</th><th className="pr-5 text-right">Accuracy</th></tr></thead><tbody>{games.map(g=><tr key={g.id} className="border-t border-white/5"><td className="px-5 py-3.5 font-medium">{g.opponent}</td><td className="text-slate-400">{g.color}</td><td className={g.result==="Win"?"text-emerald-300":g.result==="Loss"?"text-red-300":"text-cyan-300"}>{g.result}</td><td className="font-mono text-slate-500">{g.timeControl}</td><td className="pr-5 text-right font-mono">{g.accuracy?.toFixed(1)}%</td></tr>)}</tbody></table></div></div>}
